name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ connectionStatus: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Seed sample images
        run: pnpm seed:images
      - name: Lint packages (if configs exist)
        run: |
          echo "No explicit lint step configured; skipping gracefully"
      - name: Seed Mongo (remote image URLs)
        run: pnpm seed:mongo
      - name: Backend smoke start
        run: |
          cp .env.example .env
          echo "MONGO_URI=mongodb://localhost:27017/modulist" >> .env
          nohup pnpm backend:dev &
          for i in {1..20}; do
            curl -sf http://localhost:4000/health && break
            sleep 1
          done
          curl -s http://localhost:4000/health | grep -q 'ok'
      - name: Frontend build (ensures vite config compiles)
        run: pnpm --filter modulist-frontend build
      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
      - name: Run Playwright tests
        env:
          BASE_URL: http://localhost:5173
          BACKEND_URL: http://localhost:4000
        run: |
          nohup pnpm frontend:dev &
          n=0; until curl -sSf http://localhost:5173 >/dev/null; do n=$((n+1)); [ $n -gt 25 ] && exit 1; sleep 1; done
          pnpm test:e2e

